server:
  port: 19091

management:
  endpoints:
    web:
      exposure:
        include: metrics, health, info
  metrics:
    tags:
      application: user-service

spring:
  application:
    name: user-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: hikari-pool
      catalog: user
      maximum-pool-size: 13
      data-source-properties:
        idleTimeout: 600000
        maxLifetime: 1800000
        minimumIdle: 5
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      connection-test-query: select 1
      auto-commit: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        show-sql: true
        format_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
  config:
    import: classpath:application-key.yml
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

springdoc:
  use-fqn: true
  cache:
    disabled: true
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /index.html
    tags-sorter: alpha
    operations-sorter: alpha
    groups-order: asc
    display-request-duration: true
    doc-expansion: none
    disable-swagger-default-url: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

---

logging:
  level:
    org.hibernate:
      #      SQL: debug
      SQL: error
      type: error
    com.zaxxer.hikari.HikariDataSource: error

---

service:
  jwt:
    access-expiration: 360000
    secret-key: ${SECURITY_JWT_KEY}

eureka:
  instance:
    initial-status: up
    prefer-ip-address: false
    instance-id: user-service
  client:
    service-url:
      defaultZone: http://${EUREKA_NAME}:${EUREKA_PORT}/${EUREKA_HOST}/
    region: ap-northeast-2
