services:
  mysql-db:
    image: mysql:8.0.34
    container_name: mysql-delivery-route
    ports:
      - "3312:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DATASOURCE_PASSWORD}
      MYSQL_DATABASE: delivery-route
    volumes:
      - mysql-data-delivery-route:/var/lib/mysql-delivery-route
    networks:
      - default
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  mysql-data-delivery-route:

networks:
  default:
    driver: bridge
