server:
  port: 19093

management:
  endpoints:
    web:
      exposure:
        include: refresh
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT}
  tracing:
    sampling:
      probability: 1.0

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: hikari-pool
      catalog: company
      maximum-pool-size: 9
      data-source-properties:
        idleTimeout: 600000
        maxLifetime: 1800000
        minimumIdle: 5
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      connection-test-query: select 1
      auto-commit: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
          batch_size: 20
        order_insert: true
        show-sql: true
        format_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  config:
    import: classpath:application-key.yml
  cloud:
    openfeign:
      okhttp:
        enabled: true
      client:
        config:
          default:
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: FULL
      circuitbreaker:
        enabled: true
  sql:
    init:
      mode: never

---

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        slow-call-rate-threshold: 80
        slow-call-duration-threshold:
          seconds: 5
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 100
        register-health-indicator: true
        minimum-number-of-calls: 5
        wait-duration-in-open-state:
          seconds: 15
  retry:
    instances:
      hubClient:
        max-attempts: 3
        wait-duration:
          seconds: 1
        retry-exceptions:
          - com.sparta.company.domain.exception.FeignException
        ignore-exceptions:
          - jakarta.ws.rs.InternalServerErrorException

---
springdoc:
  use-fqn: true
  cache:
    disabled: true
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    groups-order: asc
    display-request-duration: true
    doc-expansion: none
    disable-swagger-default-url: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

---

logging:
  level:
    org.hibernate:
      SQL: debug
      type: error
    com.zaxxer.hikari.HikariDataSource: error

---

eureka:
  instance:
    initial-status: up
    prefer-ip-address: false
    instance-id: company-server
  client:
    service-url:
      defaultZone: http://${EUREKA_NAME}:${EUREKA_PORT}/${EUREKA_HOST}/
    region: ap-northeast-2
